"""empty message

Revision ID: 443270b01c4e
Revises: 6ed1ae87749e
Create Date: 2023-06-24 10:50:51.844312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443270b01c4e'
down_revision = '6ed1ae87749e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proprietario', schema=None) as batch_op:
        batch_op.alter_column('cod_prop_pj',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.alter_column('cod_prop_pf',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proprietario', schema=None) as batch_op:
        batch_op.alter_column('cod_prop_pf',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.alter_column('cod_prop_pj',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###
