"""empty message

Revision ID: 6ed1ae87749e
Revises: ca3e5ea829e2
Create Date: 2023-06-23 22:40:47.482193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed1ae87749e'
down_revision = 'ca3e5ea829e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dono_pj', schema=None) as batch_op:
        batch_op.alter_column('cod_prop_pj',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('cod_prop_pf',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('pessoa_fisica', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['cpf_prop'])

    with op.batch_alter_table('pessoa_juridica', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['cnpj_prop'])

    with op.batch_alter_table('proprietario', schema=None) as batch_op:
        batch_op.alter_column('cod_proprietario',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('cod_prop_pj',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('cod_prop_pf',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('proprietario_propriedade', schema=None) as batch_op:
        batch_op.alter_column('cod_propriedade',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('cod_proprietario',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proprietario_propriedade', schema=None) as batch_op:
        batch_op.alter_column('cod_proprietario',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('cod_propriedade',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('proprietario', schema=None) as batch_op:
        batch_op.alter_column('cod_prop_pf',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('cod_prop_pj',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('cod_proprietario',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('pessoa_juridica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('pessoa_fisica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('dono_pj', schema=None) as batch_op:
        batch_op.alter_column('cod_prop_pf',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('cod_prop_pj',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
